# Generated by Django 2.1.1 on 2018-09-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickrOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsid', models.CharField(max_length=200)),
                ('realname', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('iconserver', models.IntegerField()),
                ('iconfarm', models.IntegerField()),
                ('path_alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FlickrPhotoDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField()),
                ('taken', models.DateTimeField()),
                ('takengranularity', models.IntegerField()),
                ('takenunknown', models.IntegerField()),
                ('lastupdate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlickrPhotoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flickr_id', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('authorname', models.CharField(max_length=200)),
                ('raw', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('machine_tag', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FlickrPhotoUrl',
            new_name='FlickrPhotoUrls',
        ),
        migrations.RenameField(
            model_name='flickrphotourls',
            old_name='flickr_photo_id',
            new_name='flickr_photo',
        ),
        migrations.AddField(
            model_name='flickrphotos',
            name='comments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flickrphotos',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flickrphotos',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flickrphototags',
            name='flickr_photo',
            field=models.ManyToManyField(to='flickr.FlickrPhotos'),
        ),
        migrations.AddField(
            model_name='flickrphotodates',
            name='flickr_photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flickr.FlickrPhotos'),
        ),
        migrations.AddField(
            model_name='flickrowner',
            name='flickr_photo',
            field=models.ManyToManyField(to='flickr.FlickrPhotos'),
        ),
    ]
