# Generated by Django 2.1.1 on 2018-09-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0002_auto_20180923_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flickrgroup',
            old_name='flckr_id',
            new_name='flickr_id',
        ),
    ]
