# Generated by Django 2.1.1 on 2018-09-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('flickr', '0004_auto_20180923_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickrPhotoOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsid', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('realname', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('iconserver', models.IntegerField()),
                ('iconfarm', models.IntegerField()),
                ('path_alias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FlickrPhotoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='FlickrPhotoTags',
            new_name='FlickrPhotoTag',
        ),
        migrations.RemoveField(
            model_name='flickrowner',
            name='flickr_photo',
        ),
        migrations.RemoveField(
            model_name='flickrphotourls',
            name='flickr_photo',
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='flickr_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flickr.FlickrGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='originalsecret',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flickrphotodate',
            name='lastupdate',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='FlickrOwner',
        ),
        migrations.DeleteModel(
            name='FlickrPhotoUrls',
        ),
        migrations.AddField(
            model_name='flickrphotourl',
            name='flickr_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='flickr.FlickrPhoto'),
        ),
        migrations.AddField(
            model_name='flickrphotoowner',
            name='flickr_photo',
            field=models.ManyToManyField(to='flickr.FlickrPhoto'),
        ),
    ]
