# Generated by Django 2.1.1 on 2018-09-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0007_auto_20180923_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrphoto',
            name='isfamily',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='isfriend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='ispublic',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
