# Generated by Django 2.1.1 on 2018-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0008_auto_20180923_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrphoto',
            name='editability',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='geoperms',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='notes',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='people',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='publiceditability',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphoto',
            name='usage',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphotolocation',
            name='country',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphotolocation',
            name='county',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphotolocation',
            name='locality',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphotolocation',
            name='neighbourhood',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='flickrphotolocation',
            name='region',
            field=models.TextField(default='{}'),
        ),
    ]
