# Generated by Django 2.1.1 on 2018-09-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0009_auto_20180923_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrphototag',
            name='flickr_photo',
        ),
        migrations.AddField(
            model_name='flickrphototag',
            name='flickr_photo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='flickr.FlickrPhoto'),
            preserve_default=False,
        ),
    ]
