# Generated by Django 2.1.1 on 2018-09-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0010_auto_20180923_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrphotoowner',
            name='flickr_photo',
        ),
        migrations.AddField(
            model_name='flickrphotoowner',
            name='flickr_photo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='flickr.FlickrPhoto'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='flickrphototag',
            name='flickr_photo',
        ),
        migrations.AddField(
            model_name='flickrphototag',
            name='flickr_photo',
            field=models.ManyToManyField(to='flickr.FlickrPhoto'),
        ),
    ]
