# Generated by Django 2.1.1 on 2018-09-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0011_auto_20180923_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flickrphototag',
            old_name='flickr_photo',
            new_name='flickr_photos',
        ),
    ]
