# Generated by Django 2.1.1 on 2018-09-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0012_auto_20180923_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrphoto',
            name='editability',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='geoperms',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='notes',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='people',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='publiceditability',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='usage',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphotolocation',
            name='country',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphotolocation',
            name='county',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphotolocation',
            name='locality',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphotolocation',
            name='neighbourhood',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphotolocation',
            name='region',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
