# Generated by Django 2.1.1 on 2018-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0014_auto_20180923_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrphotourl',
            name='url_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
