# Generated by Django 2.1.1 on 2018-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0015_auto_20180923_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flickrphotourl',
            name='url_type',
        ),
        migrations.AddField(
            model_name='flickrphotourl',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
