# Generated by Django 2.1.1 on 2018-09-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0016_auto_20180923_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrphotourl',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
