# Generated by Django 2.1.1 on 2018-09-24 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flickr', '0017_auto_20180923_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrgroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flickr_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
