# Generated by Django 2.1.1 on 2018-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0019_auto_20180924_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrphoto',
            name='isfamily',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='isfavorite',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='isfriend',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='flickrphoto',
            name='ispublic',
            field=models.NullBooleanField(),
        ),
    ]
