# Generated by Django 2.1.1 on 2018-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0022_auto_20180924_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrphotonote',
            name='dimesions',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='flickrphototag',
            name='flickr_photos',
            field=models.ManyToManyField(related_name='tags', to='flickr.FlickrPhoto'),
        ),
    ]
